#!/usr/bin/env node
import { createHash, randomUUID } from "node:crypto";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { diskFs, writeAtomic } from "../src/fs.ts";

const SYSTEM_FOLDERS = new Set(["_accounts", "_media", "_system"]);
const BATCH_SIZE = 16;

export interface NavigationCleanupScanEntry {
  relativePath: string;
  size: number;
  sha256: string;
  profileLink: boolean;
  folderLink: boolean;
}

export interface NavigationCleanupScan {
  schemaVersion: 1;
  kind: "xmc-post-navigation-cleanup-scan";
  archiveRoot: string;
  createdAt: string;
  summary: {
    markdownFiles: number;
    postNotes: number;
    candidates: number;
    profileLinks: number;
    folderLinks: number;
    bothLinks: number;
  };
  entries: NavigationCleanupScanEntry[];
}

export interface NavigationCleanupPlanEntry extends NavigationCleanupScanEntry {
  afterSize: number;
  afterSha256: string;
}

export interface NavigationCleanupPlan {
  schemaVersion: 1;
  kind: "xmc-post-navigation-cleanup-plan";
  archiveRoot: string;
  createdAt: string;
  scanCreatedAt: string;
  summary: NavigationCleanupScan["summary"];
  entries: NavigationCleanupPlanEntry[];
}

export interface NavigationTransform {
  isPost: boolean;
  changed: boolean;
  profileLink: boolean;
  folderLink: boolean;
  output: string;
}

function sha256(value: string | Uint8Array): string {
  return createHash("sha256").update(value).digest("hex");
}

function normalizeRoot(root: string): string { return path.resolve(root); }

function safeFile(root: string, relativePath: string): string {
  if (!relativePath || path.isAbsolute(relativePath) || relativePath.includes("\\")) throw new Error("plan contains an unsafe relative path");
  const target = path.resolve(root, ...relativePath.split("/"));
  if (!target.startsWith(`${path.resolve(root)}${path.sep}`)) throw new Error("plan path escapes archive root");
  return target;
}

function relativeFile(root: string, file: string): string {
  const relative = path.relative(root, file).split(path.sep).join("/");
  safeFile(root, relative);
  return relative;
}

function navigationParts(rootName: string, folder: string): { profile: Set<string>; folder: Set<string> } {
  const profile = new Set([`[[${rootName}/${folder}/_profile|投稿者プロフィール]]`]);
  const destination = `${rootName}/${folder}/${folder}`;
  const folderLinks = new Set([
    `[[${destination}|このユーザーの投稿フォルダ]]`,
    `[[${destination}|このユーザの投稿フォルダ]]`,
  ]);
  return { profile, folder: folderLinks };
}

/** Removes only the first nonblank body line, and only when every component is
 * one of the exact links generated by XMC for that note's own author folder. */
export function removeGeneratedPostNavigation(text: string, rootName: string, folder: string): NavigationTransform {
  const eol = text.includes("\r\n") ? "\r\n" : "\n";
  const lines = text.split(/\r?\n/u);
  if (lines[0] !== "---") return { isPost: false, changed: false, profileLink: false, folderLink: false, output: text };
  const frontmatterEnd = lines.indexOf("---", 1);
  if (frontmatterEnd < 0) return { isPost: false, changed: false, profileLink: false, folderLink: false, output: text };
  const isPost = lines.slice(1, frontmatterEnd).some((line) => /^tweet_id\s*:/u.test(line));
  if (!isPost) return { isPost: false, changed: false, profileLink: false, folderLink: false, output: text };

  let navigationLine = frontmatterEnd + 1;
  while (navigationLine < lines.length && lines[navigationLine].trim() === "") navigationLine += 1;
  if (navigationLine >= lines.length) return { isPost: true, changed: false, profileLink: false, folderLink: false, output: text };

  const expected = navigationParts(rootName, folder);
  const parts = lines[navigationLine].trim().split(/\s+·\s+/u);
  const profileLink = parts.some((part) => expected.profile.has(part));
  const folderLink = parts.some((part) => expected.folder.has(part));
  const everyPartIsGenerated = parts.length > 0 && parts.every((part) => expected.profile.has(part) || expected.folder.has(part));
  if (!everyPartIsGenerated || (!profileLink && !folderLink)) {
    return { isPost: true, changed: false, profileLink: false, folderLink: false, output: text };
  }

  lines.splice(navigationLine, 1);
  if (navigationLine < lines.length && lines[navigationLine].trim() === "") lines.splice(navigationLine, 1);
  return { isPost: true, changed: true, profileLink, folderLink, output: lines.join(eol) };
}

async function batches<T, R>(items: readonly T[], task: (item: T) => Promise<R>): Promise<R[]> {
  const output: R[] = [];
  for (let offset = 0; offset < items.length; offset += BATCH_SIZE) {
    output.push(...await Promise.all(items.slice(offset, offset + BATCH_SIZE).map(task)));
  }
  return output;
}

async function markdownFiles(archiveRoot: string): Promise<string[]> {
  const entries = await fs.readdir(archiveRoot, { withFileTypes: true });
  const folders = entries.filter((entry) => entry.isDirectory() && !SYSTEM_FOLDERS.has(entry.name));
  const nested = await batches(folders, async (folder) => {
    const directory = path.join(archiveRoot, folder.name);
    const files = await fs.readdir(directory, { withFileTypes: true });
    return files.filter((file) => file.isFile() && file.name.toLowerCase().endsWith(".md"))
      .map((file) => path.join(directory, file.name));
  });
  return nested.flat().sort((left, right) => left < right ? -1 : left > right ? 1 : 0);
}

export async function scanPostNavigation(rawArchiveRoot: string): Promise<NavigationCleanupScan> {
  const archiveRoot = normalizeRoot(rawArchiveRoot);
  const rootName = path.basename(archiveRoot);
  const stat = await fs.stat(archiveRoot);
  if (!stat.isDirectory()) throw new Error("archive root is not a directory");
  const files = await markdownFiles(archiveRoot);
  let postNotes = 0;
  const inspected = await batches(files, async (file) => {
    const bytes = await fs.readFile(file);
    const folder = path.basename(path.dirname(file));
    const result = removeGeneratedPostNavigation(bytes.toString("utf8"), rootName, folder);
    if (result.isPost) postNotes += 1;
    if (!result.changed) return null;
    return {
      relativePath: relativeFile(archiveRoot, file),
      size: bytes.length,
      sha256: sha256(bytes),
      profileLink: result.profileLink,
      folderLink: result.folderLink,
    } satisfies NavigationCleanupScanEntry;
  });
  const candidates = inspected.filter((entry): entry is NavigationCleanupScanEntry => entry !== null);
  return {
    schemaVersion: 1,
    kind: "xmc-post-navigation-cleanup-scan",
    archiveRoot,
    createdAt: new Date().toISOString(),
    summary: {
      markdownFiles: files.length,
      postNotes,
      candidates: candidates.length,
      profileLinks: candidates.filter((entry) => entry.profileLink).length,
      folderLinks: candidates.filter((entry) => entry.folderLink).length,
      bothLinks: candidates.filter((entry) => entry.profileLink && entry.folderLink).length,
    },
    entries: candidates,
  };
}

function validateScan(scan: NavigationCleanupScan, archiveRoot: string): void {
  if (!scan || scan.schemaVersion !== 1 || scan.kind !== "xmc-post-navigation-cleanup-scan" || !Array.isArray(scan.entries)) {
    throw new Error("invalid post navigation scan");
  }
  if (normalizeRoot(scan.archiveRoot) !== archiveRoot) throw new Error("scan archive root does not match");
}

function validatePlan(plan: NavigationCleanupPlan, archiveRoot: string): void {
  if (!plan || plan.schemaVersion !== 1 || plan.kind !== "xmc-post-navigation-cleanup-plan" || !Array.isArray(plan.entries)) {
    throw new Error("invalid post navigation plan");
  }
  if (normalizeRoot(plan.archiveRoot) !== archiveRoot) throw new Error("plan archive root does not match");
}

export async function planPostNavigation(rawArchiveRoot: string, scan: NavigationCleanupScan): Promise<NavigationCleanupPlan> {
  const archiveRoot = normalizeRoot(rawArchiveRoot);
  validateScan(scan, archiveRoot);
  const rootName = path.basename(archiveRoot);
  const entries = await batches(scan.entries, async (entry) => {
    const file = safeFile(archiveRoot, entry.relativePath);
    const bytes = await fs.readFile(file);
    if (bytes.length !== entry.size || sha256(bytes) !== entry.sha256) throw new Error(`note changed after scan: ${entry.relativePath}`);
    const folder = entry.relativePath.split("/")[0];
    const result = removeGeneratedPostNavigation(bytes.toString("utf8"), rootName, folder);
    if (!result.changed || result.profileLink !== entry.profileLink || result.folderLink !== entry.folderLink) {
      throw new Error(`note no longer matches scan: ${entry.relativePath}`);
    }
    return { ...entry, afterSize: Buffer.byteLength(result.output), afterSha256: sha256(result.output) };
  });
  return {
    schemaVersion: 1,
    kind: "xmc-post-navigation-cleanup-plan",
    archiveRoot,
    createdAt: new Date().toISOString(),
    scanCreatedAt: scan.createdAt,
    summary: { ...scan.summary },
    entries,
  };
}

interface ApplyOptions { confirm?: boolean; backupRoot: string; receiptPath: string; }

export async function applyPostNavigation(plan: NavigationCleanupPlan, rawArchiveRoot: string, options: ApplyOptions): Promise<{ updated: number; backupRoot: string; receiptPath: string }> {
  const archiveRoot = normalizeRoot(rawArchiveRoot);
  validatePlan(plan, archiveRoot);
  if (!options.confirm) throw new Error("apply requires --confirm");
  const backupRoot = path.resolve(options.backupRoot);
  const receiptPath = path.resolve(options.receiptPath);
  try { await fs.stat(backupRoot); throw new Error("backup root already exists"); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
  try { await fs.stat(receiptPath); throw new Error("apply receipt already exists"); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }

  const rootName = path.basename(archiveRoot);
  const prepared = await batches(plan.entries, async (entry) => {
    const file = safeFile(archiveRoot, entry.relativePath);
    const bytes = await fs.readFile(file);
    if (bytes.length !== entry.size || sha256(bytes) !== entry.sha256) throw new Error(`planned note changed before apply: ${entry.relativePath}`);
    const folder = entry.relativePath.split("/")[0];
    const result = removeGeneratedPostNavigation(bytes.toString("utf8"), rootName, folder);
    if (!result.changed || Buffer.byteLength(result.output) !== entry.afterSize || sha256(result.output) !== entry.afterSha256) {
      throw new Error(`planned transform changed before apply: ${entry.relativePath}`);
    }
    return { entry, file, bytes, output: result.output, backup: safeFile(backupRoot, entry.relativePath) };
  });

  // Existence was rejected above, so recursive creation is safe here and also
  // supports a fresh private run directory whose parent has not been made yet.
  await fs.mkdir(backupRoot, { recursive: true });
  for (const item of prepared) {
    await fs.mkdir(path.dirname(item.backup), { recursive: true });
    await fs.writeFile(item.backup, item.bytes, { flag: "wx" });
    if (sha256(await fs.readFile(item.backup)) !== item.entry.sha256) throw new Error(`backup verification failed: ${item.entry.relativePath}`);
  }

  const receipt = {
    schemaVersion: 1,
    kind: "xmc-post-navigation-cleanup-apply-receipt",
    appliedAt: new Date().toISOString(),
    archiveRoot,
    planCreatedAt: plan.createdAt,
    updated: prepared.length,
    backupRoot,
    entries: prepared.map(({ entry }) => ({ relativePath: entry.relativePath, beforeSha256: entry.sha256, afterSha256: entry.afterSha256 })),
  };
  const written: typeof prepared = [];
  try {
    for (const item of prepared) {
      await writeAtomic(diskFs, item.file, item.output);
      written.push(item);
      const published = await fs.readFile(item.file);
      if (published.length !== item.entry.afterSize || sha256(published) !== item.entry.afterSha256) {
        throw new Error(`written note verification failed: ${item.entry.relativePath}`);
      }
    }
    // The receipt is part of the transaction. A disk/sync failure here must
    // not leave thousands of changed notes with no durable apply record.
    await fs.mkdir(path.dirname(receiptPath), { recursive: true });
    await fs.writeFile(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`, { flag: "wx" });
  } catch (error) {
    await fs.unlink(receiptPath).catch(() => undefined);
    const rollbackFailures: string[] = [];
    for (const item of written.reverse()) {
      try { await writeAtomic(diskFs, item.file, item.bytes); }
      catch { rollbackFailures.push(item.entry.relativePath); }
    }
    if (rollbackFailures.length > 0) throw new Error(`apply failed and rollback was incomplete: ${rollbackFailures.length} notes`, { cause: error });
    throw error;
  }
  return { updated: prepared.length, backupRoot, receiptPath };
}

export async function verifyPostNavigation(plan: NavigationCleanupPlan, rawArchiveRoot: string): Promise<{ ok: boolean; checked: number; errors: string[] }> {
  const archiveRoot = normalizeRoot(rawArchiveRoot);
  validatePlan(plan, archiveRoot);
  const errors: string[] = [];
  await batches(plan.entries, async (entry) => {
    try {
      const bytes = await fs.readFile(safeFile(archiveRoot, entry.relativePath));
      if (bytes.length !== entry.afterSize || sha256(bytes) !== entry.afterSha256) errors.push(entry.relativePath);
    } catch { errors.push(entry.relativePath); }
  });
  return { ok: errors.length === 0, checked: plan.entries.length, errors };
}

function args(argv: string[]): Record<string, string | boolean | string[]> {
  const output: Record<string, string | boolean | string[]> = { _: [] };
  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index];
    if (!value.startsWith("--")) (output._ as string[]).push(value);
    else if (value === "--confirm") output.confirm = true;
    else output[value.slice(2)] = argv[++index];
  }
  return output;
}

async function readJson<T>(file: string): Promise<T> { return JSON.parse(await fs.readFile(path.resolve(file), "utf8")) as T; }
async function writeJsonExclusive(file: string, value: unknown): Promise<void> {
  const target = path.resolve(file);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, `${JSON.stringify(value, null, 2)}\n`, { flag: "wx" });
}

async function main(argv: string[]): Promise<void> {
  const parsed = args(argv); const command = (parsed._ as string[])[0];
  const archive = typeof parsed.archive === "string" ? parsed.archive : "";
  if (!command || !archive) throw new Error("usage: post-navigation-cleanup <scan|plan|apply|verify> --archive ABSOLUTE_XMediaArchive [options]");
  if (command === "scan") {
    if (typeof parsed.out !== "string") throw new Error("scan requires --out");
    const report = await scanPostNavigation(archive); await writeJsonExclusive(parsed.out, report); console.log(JSON.stringify(report.summary)); return;
  }
  if (command === "plan") {
    if (typeof parsed.scan !== "string" || typeof parsed.out !== "string") throw new Error("plan requires --scan and --out");
    const plan = await planPostNavigation(archive, await readJson<NavigationCleanupScan>(parsed.scan));
    await writeJsonExclusive(parsed.out, plan); console.log(JSON.stringify(plan.summary)); return;
  }
  if (typeof parsed.plan !== "string") throw new Error(`${command} requires --plan`);
  const plan = await readJson<NavigationCleanupPlan>(parsed.plan);
  if (command === "apply") {
    const runDirectory = path.dirname(path.resolve(parsed.plan));
    const result = await applyPostNavigation(plan, archive, {
      confirm: parsed.confirm === true,
      backupRoot: path.join(runDirectory, "backup"),
      receiptPath: path.join(runDirectory, `apply-receipt-${randomUUID()}.json`),
    });
    console.log(JSON.stringify(result)); return;
  }
  if (command === "verify") {
    const result = await verifyPostNavigation(plan, archive); console.log(JSON.stringify(result)); if (!result.ok) process.exitCode = 2; return;
  }
  throw new Error(`unknown command: ${command}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => { console.error((error as Error).message); process.exitCode = 1; });
}
